# Generated by Django 5.2.1 on 2025-06-03 11:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите название товара", max_length=50, verbose_name="Название"),
                ),
                (
                    "model_product",
                    models.CharField(
                        blank=True, help_text="Введите модель ", max_length=200, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        default=datetime.datetime(2025, 6, 3, 16, 53, 0, 411826),
                        help_text="Введите дату выхода продукта на рынок",
                        verbose_name="Дата выхода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
