# Generated by Django 5.2.1 on 2025-06-06 18:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название фирмы-постащика", max_length=100, verbose_name="Название фирмы"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Введите страну", max_length=100, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Введите название фирмы-поставщика",
                        max_length=100,
                        null=True,
                        verbose_name="Город",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Введите адрес фирмы-поставщика (улица, № дома)",
                        null=True,
                        verbose_name="Адрес поставщика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Введите дату выхода продукта на рынок",
                verbose_name="Дата выхода",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Укажите задолжность перед поставщиком",
                        max_digits=10,
                        verbose_name="Задолжность",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Уровень в иерархии",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Введите товар",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="suppliers.product",
                        verbose_name="Товара",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Введите заказчика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_customer",
                        to="suppliers.supplier",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Введите поставщика",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="suppliers.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
