# Generated by Django 5.2.1 on 2025-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_supplier_alter_product_release_date_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="type",
            field=models.CharField(
                choices=[
                    ("factory", "завод"),
                    ("retail", "розничная сеть"),
                    ("entrepreneur", "индивидуальный предприниматель"),
                ],
                default="factory",
                max_length=35,
                verbose_name="тип юридического лица",
            ),
        ),
    ]
